import {
  Users,
  UserCog,
  GraduationCap,
  BookOpen,
  ClipboardList,
  FilePen,
  BarChart2,
  UserCircle,
  Settings,
  SchoolIcon,
  Building2,
  PiggyBank,
  BookOpenTextIcon,
  TrendingUp,
  EyeIcon,
} from "lucide-react";

export const iconMap: Record<string, React.ElementType> = {
  users: Users,
  "user-cog": UserCog,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "clipboard-list": ClipboardList,
  "file-pen": FilePen,
  "bar-chart-2": BarChart2,
  "user-circle": UserCircle,
  settings: Settings,
  "chalkboard-teacher": SchoolIcon,
  "building-two": Building2,
  "piggy-bank": PiggyBank,
  "book-open-text": BookOpenTextIcon,
  "trending-up": TrendingUp,
  "eye-icon": EyeIcon,
};
