import {
  TbUsers,
  TbUserCog,
  TbSchool,
  TbBook,
  TbClipboardList,
  TbFilePencil,
  TbChartHistogram,
  TbUserCircle,
  TbSettings,
  TbChalkboard,
  TbBuildingSkyscraper,
  TbPig,
  TbTrendingUp,
  TbEye,
} from "react-icons/tb";

export const iconMap: Record<string, React.ElementType> = {
  users: TbUsers,
  "user-cog": TbUserCog,
  "graduation-cap": TbSchool,
  "book-open": TbBook,
  "clipboard-list": TbClipboardList,
  "file-pen": TbFilePencil,
  "bar-chart-2": TbChartHistogram,
  "user-circle": TbUserCircle,
  settings: TbSettings,
  "chalkboard-teacher": TbChalkboard,
  "building-two": TbBuildingSkyscraper,
  "piggy-bank": TbPig,
  "book-open-text": TbBook,
  "trending-up": TbTrendingUp,
  "eye-icon": TbEye,
};
